[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  autoLaunch = false